### ISSUE TITLE
Find missing thumbs

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/ensemble-at-yale#104]
there are missing thumbs that should be found; examples:
https://s3-us-west-2.amazonaws.com/lab-apps/ensemble-at-yale/page-thumbs-revised/dra037-s01-b003-f038-i05-p0006.jpg

https://s3-us-west-2.amazonaws.com/lab-apps/ensemble-at-yale/page-thumbs-revised/dra037-s01-b003-f038-i03-p0010.jpg 

https://s3-us-west-2.amazonaws.com/lab-apps/ensemble-at-yale/page-thumbs-revised/dra037-s01-b016-f208-i03-p0001.jpg

**Comment by pleonard212** [comment]
https://s3-us-west-2.amazonaws.com/lab-apps/ensemble-at-yale/page-thumbs-revised/dra037-s01-b017-f223-i02-p0002.jpg

**Comment by duhaime** [comment]
It looks like there are [~190 images](https://github.com/YaleDHLab/ensemble-at-yale/blob/master/project/ensemble-at-yale/build_group_csv_files/missing_images.txt) that are identified in the master project spreadsheets but not loaded into AWS. Peter and I looked at a few of these and it seems like the image files are actually not present in the Box folders. @lindsaymking would your team be able to take a look into these missing image files?

**Comment by lindsaymking** [comment]
Yes, we'll take a look and see what's going on.

**Comment by duhaime** [comment]
Merci!

**Comment by lindsaymking** [comment]
I've resolved the majority of the filename issues on the server and the spreadsheets (the definitive versions of the data), so upon reingest all but a few programs (which we may need to rescan) should go through smoothly. 

Peter and I will also have the PDF program files and spreadsheet ready to go by early next week so that we can add those and have Bundy's era represented more fully!

**Comment by duhaime** [comment]
Woohoo! Thank you!

**Comment by lindsaymking** [comment]
Completed PDF spreadsheet and files are up on Box, ready to ingest! It will be great to have those in when I show Ensemble to James.
