### ISSUE TITLE
Mark: Complete State not sticking

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/ensemble-at-yale#121]
After a field is marked, the button for that goes to a complete state, which reflects a checkbox on the button. I notice that if one clicks to another page in a multi-page program, this completed state does not stick and the buttons seems to reset when you go to a different page.

**Comment by duhaime** [comment]
A quick note on this issue: We can correctly represent completed tasks by passing `@state.subjectSets` from the Mark index.cjsx file to the `TaskComponent` (which resolves to `pick-one-mark-one.cjsx` in our case). I'll implement these changes so we can see what they look like. 

Because we need to iterate over all marks both deleted and present to determine which are still active (and which were made by the current user) though, we may wish to remove this state advertisement altogether for performance reasons.

**Comment by duhaime** [comment]
This is now deployed, and happily it seems this comprehensive sweep of the props is fast enough on AWS!
