### ISSUE TITLE
Increase transcription threshold to 3 for retirement

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#149]
Put retired plays back to work

**Comment by duhaime** [comment]
Reading through this app, it appears this is set by `db.workflows.findOne({'name': 'transcribe'}).generates_subjects_after`, currently set to 1.

This was correctly set via the [configuration for the transcribe step](https://github.com/YaleDHLab/ensemble-at-yale/blob/master/project/ensemble-at-yale/workflows/transcribe.json#L7).

I'm remembering now we only needed to change retirement from mark because we had multiple subjects that belong to a subject set--we didn't need to touch the transcription retirement logic.

**Comment by duhaime** [comment]
This seems to be resolved simply via mongo:

```
db.workflows.update({'name': 'transcribe'}, {$set: {'generates_subjects_after': 2}})

> db.workflows.findOne({'name': 'transcribe'}).generates_subjects_after
2
```

**Comment by duhaime** [comment]
To unretire everyone, we can use:

```
 db.subject_set_first_pages.update({}, {$set: {'retired_from_mark': 0, 'retired_from_transcribe': 0}}, {multi: true})
```

**Comment by pleonard212** [comment]
Thanks!
